name: MyFirstCI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Запускаю скрипт
      run: | 
           echo %GITHUB_WORKSPACE%
           echo %HOME%
           echo Send file
           @ftp -i -s:"%~f0"&GOTO:EOF
           open files.000webhost.com
           unrated-circuitry
           cWou@UfKhb)RftnDwjVS
           cd public_html
           pwd
           put d:\a\FirstRepository\FirstRepository\index.html
           disconnect
      shell: cmd
