name: MyFirstCI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Запускаю скрипт
      run: | 
           echo %GITHUB_WORKSPACE%
           echo %HOME%
           echo Send file
           cd /D d:\a\FirstRepository\FirstRepository\
           dir
           ftpRun.cmd
      shell: cmd
