name: MyFirstCI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Запускаю скрипт
      run: | 
           echo Send file
           ftp
           open files.000webhost.com
           unrated-circuitry
           cWou@UfKhb)RftnDwjVS
           cd public_html
           pwd
           put index.html
           disconnect
      shell: cmd
